!     ######spl
      MODULE MODD_EMUL
!     ################
!
!
LOGICAL :: LEMULPART3D=.FALSE.
LOGICAL :: LEMUL1D=.FALSE.
LOGICAL :: LEMUL1=.FALSE.
LOGICAL :: LPROCP1=.FALSE.
LOGICAL :: LMASK=.FALSE.

END MODULE MODD_EMUL
