MODULE MODD_DIAG_TRIP_n

CONTAINS
!
SUBROUTINE DIAG_TRIP_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
END SUBROUTINE DIAG_TRIP_GOTO_MODEL

SUBROUTINE DIAG_TRIP_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
END SUBROUTINE DIAG_TRIP_ALLOC

SUBROUTINE DIAG_TRIP_DEALLO
END SUBROUTINE DIAG_TRIP_DEALLO
END MODULE MODD_DIAG_TRIP_n  
!##################
!##################
!##################
MODULE MODD_TRIP_GRID_n
CONTAINS

SUBROUTINE TRIP_GRID_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
END SUBROUTINE TRIP_GRID_GOTO_MODEL

SUBROUTINE TRIP_GRID_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
END SUBROUTINE TRIP_GRID_ALLOC

SUBROUTINE TRIP_GRID_DEALLO
END SUBROUTINE TRIP_GRID_DEALLO

END MODULE MODD_TRIP_GRID_n  
!##################
!##################
!##################   
MODULE MODD_TRIP_n
CONTAINS
!
SUBROUTINE TRIP_GOTO_MODEL(KFROM, KTO, LKFROM)
LOGICAL, INTENT(IN) :: LKFROM
INTEGER, INTENT(IN) :: KFROM, KTO
END SUBROUTINE TRIP_GOTO_MODEL

SUBROUTINE TRIP_ALLOC(KMODEL)
INTEGER, INTENT(IN) :: KMODEL
END SUBROUTINE TRIP_ALLOC

SUBROUTINE TRIP_DEALLO
END SUBROUTINE TRIP_DEALLO
!
END MODULE MODD_TRIP_n
!##################
!##################
!##################
MODULE MODD_TRIP_PAR
END MODULE MODD_TRIP_PAR
!##################
!##################
!##################     
SUBROUTINE READ_NAMELISTS_TRIP_n(HPROGRAM)
 CHARACTER(LEN=*),  INTENT(IN)     :: HPROGRAM    
END SUBROUTINE READ_NAMELISTS_TRIP_n

