!     #########
SUBROUTINE READ_NAMELISTS_BLOWSNW(HPROGRAM)
!     #######################################################
!
USE MODI_DEFAULT_BLOWSNW
!
USE MODI_READ_DEFAULT_BLOWSNW
!
USE MODI_READ_BLOWSNW_CONF
!
!
USE YOMHOOK   ,ONLY : LHOOK,   DR_HOOK
USE PARKIND1  ,ONLY : JPRB
!
IMPLICIT NONE
!
 CHARACTER(LEN=6), INTENT(IN)  :: HPROGRAM ! program calling BLOWSNW
REAL(KIND=JPRB) :: ZHOOK_HANDLE
!
!-----------------------------------------------------
!
IF (LHOOK) CALL DR_HOOK('READ_NAMELISTS_BLOWSNW',0,ZHOOK_HANDLE)
 CALL DEFAULT_BLOWSNW
!
 CALL READ_DEFAULT_BLOWSNW(HPROGRAM)
!
 CALL READ_BLOWSNW_CONF(HPROGRAM)
IF (LHOOK) CALL DR_HOOK('READ_NAMELISTS_BLOWSNW',1,ZHOOK_HANDLE)
!
!
END SUBROUTINE READ_NAMELISTS_BLOWSNW
