#!/bin/sh
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
set -x
set -e

rm -f 16JAN* OUT*  EXSEG?.nam 

ln -sf  ../004_arp2lfi/16JAN_06_MNH*.{des,lfi,nc} .
ln -sf  ../006_preal/16JAN_06_MNH2*.{des,lfi,nc} .
ln -sf  ../003_nest/16JAN98_36km.neste1.{des,lfi,nc} .
ln -sf  ../003_nest/16JAN98_9km.neste1.{des,lfi,nc} .

if [ "x${MNH_ECRAD}" != "x" ]  ; then
ln -sf ${SRC_MESONH}/src/LIB/RAD/ecrad-1.0.1/data/RAD* .
ln -sf ${SRC_MESONH}/src/LIB/RAD/ecrad-1.0.1/data/*.nc .
sed -e's/ECMW/ECRA/g' EXSEG1.nam.src > EXSEG1.nam
sed -e's/ECMW/ECRA/g' EXSEG2.nam.src > EXSEG2.nam
else
cp EXSEG1.nam.src EXSEG1.nam
cp EXSEG2.nam.src EXSEG2.nam
fi


time ${MPIRUN} MESONH${XYZ}
