!MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
!MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
!MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
!MNH_LIC for details. version 1.
C
C       FONCTION SERVANT A RENDRE FATALE OU NON UNE ERREUR DETECTEE,
C       A L'AIDE DU CODE-REPONSE COURANT, DU NIVEAU DE FILTRAGE GLOBAL,
C       ET DE L'OPTION D'ERREUR FATALE PROPRE AU FICHIER.
C       S'IL N'Y A PAS DE FICHIER (I5678=0, D'OU DIMENSIONNEMENT DE
C          *LERFAT*), LE NIVEAU DE FILTRAGE JOUE LE ROLE PRINCIPAL.
C
      INTEGER IXNIMS, I1234, I5678, I3456, IXC, IXM, IXT, IABCDE, IFGHIJ
      INTEGER IKLMNO, IPQRST, IUVWXY, IZABCD, IEFGHI
C
      LOGICAL LLMOER
C
      LLMOER (I1234,I5678)=I1234.EQ.-16.OR.
     S (I1234.NE.0.AND.(NERFAG.EQ.0.OR.(NERFAG.EQ.1.AND.LERFAT(I5678))))
C
C       FONCTION DONNANT LE PLUS HAUT NIVEAU DE MESSAGERIE ACCEPTABLE
C       POUR L'UNITE LOGIQUE DE RANG "I3456" .
C       (UTILISATION DES NIVEAUX DE MESSAGERIE GLOBAL ET PROPRE AU
C        FICHIER - MEME REMARQUE QUE CI-DESSUS SI I3456=0, POUR NIVMES)
C
      IXNIMS (I3456)=MIN0 (2,2*NIMESG,MAX0 (2*NIMESG-2,NIVMES(I3456)))
C
C       Fonctions servant a l'adressage 1D dans les tableaux CNOMAR,
C     MLGPOS et MDES1D, MTAMPD.
C
      IXC (IABCDE,IFGHIJ) = IABCDE + JPNXNA * ( IFGHIJ - 1 )
      IXM (IKLMNO,IPQRST) = IKLMNO + JPLARD * ( IPQRST - 1 )
      IXT (IUVWXY,IZABCD,IEFGHI) = IUVWXY + JPLARD *
     S ( MFACTM(IEFGHI) * IZABCD + JPNPDF * ( IEFGHI - 1 ) )
C
