!     ####################
      MODULE MODI_TIT_TRA3D
!     ####################
INTERFACE
!
      SUBROUTINE TIT_TRA3D(HCAR,HTEM1,HTEM2,PVR)
CHARACTER(LEN=75)  :: HCAR
CHARACTER(LEN=*)   :: HTEM1,HTEM2
REAL               :: PVR
END SUBROUTINE TIT_TRA3D
END INTERFACE
END MODULE MODI_TIT_TRA3D
!     ####################
      SUBROUTINE TIT_TRA3D(HCAR,HTEM1,HTEM2,PVR)
!     ####################
!
USE MODD_TIT
USE MODD_RESOLVCAR
!
IMPLICIT NONE
!
CHARACTER(LEN=75)  :: HCAR
CHARACTER(LEN=*)   :: HTEM1,HTEM2
REAL               :: PVR
!
CHARACTER(LEN=60)  :: YTEM
CHARACTER(LEN=40)  :: YTEM40
CHARACTER(LEN=75)  :: YPLANH
REAL               :: ZXPOSTITT1,ZXYPOSTITT1
REAL               :: ZXPOSTITT2,ZXYPOSTITT2
REAL               :: ZXPOSTITT3,ZXYPOSTITT3
REAL               :: ZXPOSTITB1,ZXYPOSTITB1
REAL               :: ZXPOSTITB2,ZXYPOSTITB2
REAL               :: ZXPOSTITB3,ZXYPOSTITB3
REAL               :: ZSZTITVAR1,ZSZTITVAR2
REAL               :: ZSZTITVAR3
!
! Titres  TOP
!***********************************************
! Titre N1 TOP
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  YPLANH=' '
  YPLANH=HCAR
  ZXPOSTITT1=.002
  ZXYPOSTITT1=.98
  IF(XPOSTITT1 /= 0.)THEN
    ZXPOSTITT1=XPOSTITT1
  ENDIF
  IF(XYPOSTITT1 /= 0.)THEN
    ZXYPOSTITT1=XYPOSTITT1
  ENDIF
! WRITE(YPLANH,1001)NIINF,NISUP,NJINF,NJSUP
  CALL RESOLV_TIT('CTITT1',YPLANH)
  IF(YPLANH /= ' ')THEN
    IF(XSZTITT1 /= 0.)THEN
      CALL PCSETC('FC','/')
      CALL PLCHHQ(ZXPOSTITT1,ZXYPOSTITT1,YPLANH,XSZTITT1,0.,-1.)
      CALL PCSETC('FC',':')
!     CALL PLCHHQ(0.002,0.98,YPLANH,XSZTITT1,0.,-1.)
    ELSE
      CALL PCSETC('FC','/')
      CALL PLCHHQ(ZXPOSTITT1,ZXYPOSTITT1,YPLANH,.012,0.,-1.)
      CALL PCSETC('FC',':')
!     CALL PLCHHQ(0.002,0.98,YPLANH,.012,0.,-1.)
    ENDIF
  ENDIF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! TOP2
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  YTEM(1:LEN(YTEM))=' '
  ZXPOSTITT2=.002
  ZXYPOSTITT2=.95
  IF(XPOSTITT2 /= 0.)THEN
    ZXPOSTITT2=XPOSTITT2
  ENDIF
  IF(XYPOSTITT2 /= 0.)THEN
    ZXYPOSTITT2=XYPOSTITT2
  ENDIF
  CALL RESOLV_TIT('CTITT2',YTEM)
  IF(YTEM /= ' ')THEN
    IF(XSZTITT2 /= 0.)THEN
      CALL PLCHHQ(ZXPOSTITT2,ZXYPOSTITT2,YTEM,XSZTITT2,0.,-1.)
!     CALL PLCHHQ(0.002,0.95,YTEM,XSZTITT2,0.,-1.)
    ELSE
      CALL PLCHHQ(ZXPOSTITT2,ZXYPOSTITT2,YTEM,.008,0.,-1.)
!     CALL PLCHHQ(0.002,0.95,YTEM,.008,0.,-1.)
    ENDIF
  ENDIF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! TOP3
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  ZXPOSTITT3=.002
  ZXYPOSTITT3=.93
  IF(XPOSTITT3 /= 0.)THEN
    ZXPOSTITT3=XPOSTITT3
  ENDIF
  IF(XYPOSTITT3 /= 0.)THEN
    ZXYPOSTITT3=XYPOSTITT3
  ENDIF
  YTEM(1:LEN(YTEM))=' '
  CALL RESOLV_TIT('CTITT3',YTEM)
  IF(YTEM /= ' ')THEN
    IF(XSZTITT3 /= 0.)THEN
      CALL PLCHHQ(ZXPOSTITT3,ZXYPOSTITT3,YTEM,XSZTITT3,0.,-1.)
!     CALL PLCHHQ(0.002,0.93,YTEM,XSZTITT3,0.,-1.)
    ELSE
      CALL PLCHHQ(ZXPOSTITT3,ZXYPOSTITT3,YTEM,.008,0.,-1.)
!     CALL PLCHHQ(0.002,0.93,YTEM,.008,0.,-1.)
    ENDIF
  ENDIF
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Titres  BOTTOM
!***********************************************
! Titre N1 BOTTOM
  ZXPOSTITB1=.002
  ZXYPOSTITB1=.005
  IF(XPOSTITB1 /= 0.)THEN
    ZXPOSTITB1=XPOSTITB1
  ENDIF
  IF(XYPOSTITB1 /= 0.)THEN
    ZXYPOSTITB1=XYPOSTITB1
  ENDIF
  CALL RESOLV_TIT('CTITB1',HTEM1)
  if(nverbia > 0)then
    print *,' *CTITB1=',HTEM1
  endif
  IF(HTEM1 /= ' ')THEN
    IF(XSZTITB1 /= 0.)THEN
      CALL PLCHHQ(ZXPOSTITB1,ZXYPOSTITB1,HTEM1(1:LEN_TRIM(HTEM1)),XSZTITB1,0.,-1.)
    ELSE
      CALL PLCHHQ(ZXPOSTITB1,ZXYPOSTITB1,HTEM1(1:LEN_TRIM(HTEM1)),.007,0.,-1.)
    ENDIF
  ENDIF
! Titre N3 BOTTOM
  ZXPOSTITB3=.002
  ZXYPOSTITB3=.045
  IF(XPOSTITB3 /= 0.)THEN
    ZXPOSTITB3=XPOSTITB3
  ENDIF
  IF(XYPOSTITB3 /= 0.)THEN
    ZXYPOSTITB3=XYPOSTITB3
  ENDIF

  YTEM(1:LEN(YTEM))=' '
! YTEM=CTIMEC
  YTEM=ADJUSTL(YTEM)
  CALL RESOLV_TIT('CTITB3',YTEM)
	  if(nverbia > 0)then
! print *,' image LEN et CTIMEC ',LEN(CTIMEC),CTIMEC
! print *,' image LEN et YTEM ',LEN(YTEM),YTEM
  print *,' *CTITB3=',YTEM
	  endif
  IF(YTEM/= ' ')THEN
    IF(XSZTITB3 /= 0.)THEN
      CALL PLCHHQ(ZXPOSTITB3,ZXYPOSTITB3,YTEM(1:LEN_TRIM(YTEM)),XSZTITB3,0.,-1.)
    ELSE
      CALL PLCHHQ(ZXPOSTITB3,ZXYPOSTITB3,YTEM(1:LEN_TRIM(YTEM)),.009,0.,-1.)
    ENDIF
  ENDIF

! Titre N2 BOTTOM
  ZXPOSTITB2=.002
  ZXYPOSTITB2=.025
  IF(XPOSTITB2 /= 0.)THEN
    ZXPOSTITB2=XPOSTITB2
  ENDIF
  IF(XYPOSTITB2 /= 0.)THEN
    ZXYPOSTITB2=XYPOSTITB2
  ENDIF
  CALL RESOLV_TIT('CTITB2',HTEM2)
  if(nverbia > 0)then
    print *,' *CTITB2=',HTEM2
  endif
  IF(HTEM2 /= ' ')THEN
    IF(XSZTITB2 /= 0.)THEN
      CALL PLCHHQ(0.002,0.025,HTEM2,XSZTITB2,0.,-1.)
    ELSE
      CALL PLCHHQ(0.002,0.025,HTEM2,.007,0.,-1.)
    ENDIF
  ENDIF
!
!!!!!! CTITVAR
 YTEM40(1:LEN(YTEM40))=' '
 CALL RESOLV_TIT('CTITVAR1',YTEM40)
 YTEM40=ADJUSTL(YTEM40)
 IF(YTEM40  /= ' ')THEN
  ZSZTITVAR1=.011
  IF(XSZTITVAR1 /= 0.)THEN
    ZSZTITVAR1=XSZTITVAR1
  ENDIF
!! print *,' *YTEM40 ',YTEM40(1:LEN_TRIM(YTEM40))
 CALL PLCHHQ(MAX(PVR,.99),.007,YTEM40(1:LEN_TRIM(YTEM40)),ZSZTITVAR1,0.,+1.)
 ENDIF
 YTEM40(1:LEN(YTEM40))=' '
 CALL RESOLV_TIT('CTITVAR2',YTEM40)
 IF(YTEM40  /= ' ')THEN
  ZSZTITVAR2=.011
  IF(XSZTITVAR2 /= 0.)THEN
    ZSZTITVAR2=XSZTITVAR2
  ENDIF
 CALL PLCHHQ(MAX(PVR,.99),.007+.017,YTEM40(1:LEN_TRIM(YTEM40)),ZSZTITVAR2,0.,+1.)
 ENDIF
 YTEM40(1:LEN(YTEM40))=' '
 CALL RESOLV_TIT('CTITVAR3',YTEM40)
 IF(YTEM40  /= ' ')THEN
  ZSZTITVAR3=.011
  IF(XSZTITVAR3 /= 0.)THEN
    ZSZTITVAR3=XSZTITVAR3
  ENDIF
 CALL PLCHHQ(MAX(PVR,.99),.007+.034,YTEM40(1:LEN_TRIM(YTEM40)),ZSZTITVAR3,0.,+1.)
 ENDIF
!
! Titres en X et Y
!*****************************************

END SUBROUTINE TIT_TRA3D
