#!/bin/sh
#MNH_LIC Copyright 1994-2014 CNRS, Meteo-France and Universite Paul Sabatier
#MNH_LIC This is part of the Meso-NH software governed by the CeCILL-C licence
#MNH_LIC version 1. See LICENSE, CeCILL-C_V1-en.txt and CeCILL-C_V1-fr.txt  
#MNH_LIC for details. version 1.
set -x
set -e
rm -f 16JAN* *spa04.{des,lfi,nc} OUTPUT_LISTING* pipe* *.tex
ln -sf  ../003_nest/16JAN98_9km.neste1.{des,lfi,nc} .
ln -sf  ../003_nest/16JAN98_36km.neste1.{des,lfi,nc} .
ln -sf  ../004_arp2lfi/16JAN_06_MNH.*{des,lfi,nc} .
time ${MPIRUN} SPAWNING${XYZ}             
#ddd --directory=~/DEV/MNH.V4.6.2/src/dir_obj_bug2_nest SPAWNING${XYZ}
